dist: xenial
language: node_js

node_js:
    - "8"
    - "10"
    - "stable"

cache:
    directories:
        - "node_modules"
services:
    - xvfb

env:
    - CXX=g++-6

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - mesa-utils
            - libgl1-mesa-dri
            - libglapi-mesa
            - libosmesa6
            - libxi-dev
